### ISSUE TITLE
Building Locally

### ISSUE THREAD

**Issue by shoeswat** [stamen/ecoengine#158]
[08:14:04] 'set-env' errored after 565 μs
Error: Cannot find module '/home/yoshi/.src/compare/.env.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/yoshi/.src/compare/node_modules/gulp-env/index.js:5:15)
    at Gulp.gulp.task.gulp.src.pipe.jshint.predef (/home/yoshi/.src/compare/Gulpfile.js:61:3)
    at module.exports (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:134:8)

I see that there's a .env.json.sample, so I made a copy and reran the build. I didn't get a chance to see if this worked though because I broke the local copy of holos. So I'll update this as soon as I get the website running locally again.

**Comment by postfalk** [comment]
Move/copy template .env.json.sample to .env.json.

Pls, close if it works.

On Fri, May 1, 2015 at 9:08 AM, Yugarshi Mondal <notifications@github.com>
wrote:

> [08:14:04] 'set-env' errored after 565 μs
> Error: Cannot find module '/home/yoshi/.src/compare/.env.json'
> at Function.Module._resolveFilename (module.js:338:15)
> at Function.Module._load (module.js:280:25)
> at Module.require (module.js:364:17)
> at require (module.js:380:17)
> at module.exports
> (/home/yoshi/.src/compare/node_modules/gulp-env/index.js:5:15)
> at Gulp.gulp.task.gulp.src.pipe.jshint.predef
> (/home/yoshi/.src/compare/Gulpfile.js:61:3)
> at module.exports
> (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
> at Gulp.Orchestrator._runTask
> (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
> at Gulp.Orchestrator._runStep
> (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
> at Gulp.Orchestrator.start
> (/home/yoshi/.src/compare/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
>
> I see that there's a .env.json.sample, so I made a copy and reran the
> build. I didn't get a chance to see if this worked though because I broke
> the local copy of holos. So I'll update this as soon as I get the website
> running locally again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/158>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
I realized I added that step to ecoengine-compare but on ecoengine. I have added it
https://github.com/stamen/ecoengine/blob/master/README.md#how-do-i-run-the-project-locally
